name: Lint dbdocs

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint dbdocs
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dbdocs
        run: bun install -g dbdocs

      - name: Check dbdocs
        run: dbdocs

      - name: Validate dbdocs
        run: dbdocs validate database.dbml
